name: tag_along
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  amplify_api: ^1.4.0
  amplify_authenticator: ^1.4.2
  amplify_flutter: ^1.4.1
  firebase_auth: ^4.9.0
  firebase_core: ^2.15.1
  firebase_database: ^10.2.5
  flutter:
    sdk: flutter
  go_router: ^12.0.0
  google_fonts: ^5.1.0
  velocity_x: ^4.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
